<img src="{{ $attributes->get('src') }}" {{ $attributes->except('src') }} />

{{-- <x-curator-glider 
{{ $attributes->merge(['class' => 'object-cover']) }}
:media="5"
curation="thumbnaild"
glide=""
fallback=""
background=""
blur=""
border=""
brightness=""
contrast=""
crop=""
device-pixel-ratio="1/100"
filter=""
fit=""
flip=""
format="webp"
gamma=""
height="100"
quality="70"
orientation=""
pixelate=""
sharpen=""
width="500"
watermark-path=""
watermark-width=""
watermark-height=""
watermark-x-offset=""
watermark-y-offset=""
watermark-padding=""
watermark-position=""
watermark-alpha=""
/> --}}
